language: node_js
node_js:
  - 'stable'
branches:
  only:
  - master
install:
  - npm prune
  - npm uninstall typescript
  - npm uninstall uglify-js
  - npm install typescript -g
  - npm install uglify-js -g
script:
  - npm run clean-dist
  - npm run clean-temp
  - npm run build
  - npm run create-dist
  - npm run uglifyjs
  - npm run clean-temp
cache:
  directories:
    - node_modules